# Generated by Django 4.2.21 on 2025-05-15 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ledger", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="entry",
            name="note",
            field=models.CharField(blank=True, max_length=100, verbose_name="名目"),
        ),
    ]
