# Generated by Django 4.2.21 on 2025-05-19 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ledger", "0003_goal"),
    ]

    operations = [
        migrations.AddField(
            model_name="entry",
            name="category",
            field=models.CharField(
                blank=True,
                choices=[
                    ("食費", "食費"),
                    ("交通費", "交通費"),
                    ("光熱費", "光熱費"),
                    ("趣味", "趣味"),
                    ("医療", "医療"),
                    ("交際費", "交際費"),
                    ("その他", "その他"),
                ],
                max_length=10,
                null=True,
                verbose_name="カテゴリ",
            ),
        ),
    ]
